[project]
name = "ticagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.2",
    "authlib>=1.8.0",
    "django>=6.1.1",
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "fastapi-mail>=1.6.8",
    "google-api-python-client>=2.200.0",
    "google-auth>=2.57.1",
    "google-auth-oauthlib>=1.4.1",
    "groq>=1.7.0",
    "httpx>=0.28.1",
    "itsdangerous>=2.2.0",
    "jose[jwt]>=1.0.0",
    "langchain>=1.4.0",
    "langgraph>=1.2.11",
    "pwdlib[argon2]>=0.3.1",
    "pyjwt[crypto]>=2.13.0",
    "python-jose>=3.5.0",
    "python-multipart>=0.0.32",
    "send-mail>=0.0.2",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]
